// Fruits Category - 30 Products with Real Unsplash Images

import { Product } from "./vegetables";

export const fruits: Product[] = [
  {
    id: "fruit-1",
    name: "Fresh Bananas",
    description: "Sweet, ripe bananas packed with potassium. Perfect for smoothies and snacking.",
    price: 50,
    originalPrice: 65,
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&q=80",
    category: "fruits",
    rating: 4.8,
    reviews: 456,
    isOrganic: true,
    isFresh: true,
    unit: "per dozen",
    stock: 200,
  },
  {
    id: "fruit-2",
    name: "Red Apples",
    description: "Crisp, juicy red apples from hill orchards. Packed with fiber and vitamins.",
    price: 180,
    originalPrice: 220,
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&q=80",
    category: "fruits",
    rating: 4.9,
    reviews: 387,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 150,
  },
  {
    id: "fruit-3",
    name: "Alphonso Mango",
    description: "The king of mangoes! Sweet, aromatic Alphonso mangoes from Ratnagiri.",
    price: 450,
    originalPrice: 550,
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&q=80",
    category: "fruits",
    rating: 5.0,
    reviews: 534,
    isOrganic: true,
    isFresh: true,
    unit: "per dozen",
    stock: 80,
  },
  {
    id: "fruit-4",
    name: "Fresh Oranges",
    description: "Juicy Nagpur oranges bursting with Vitamin C. Sweet and tangy flavor.",
    price: 120,
    originalPrice: 150,
    image: "https://images.unsplash.com/photo-1547514701-42782101795e?w=400&q=80",
    category: "fruits",
    rating: 4.7,
    reviews: 298,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 120,
  },
  {
    id: "fruit-5",
    name: "Green Grapes",
    description: "Sweet, seedless green grapes perfect for snacking and fruit salads.",
    price: 140,
    originalPrice: 170,
    image: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400&q=80",
    category: "fruits",
    rating: 4.8,
    reviews: 267,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 100,
  },
  {
    id: "fruit-6",
    name: "Fresh Papaya",
    description: "Ripe, orange papaya rich in enzymes. Great for digestion and breakfast.",
    price: 60,
    originalPrice: 80,
    image: "https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?w=400&q=80",
    category: "fruits",
    rating: 4.6,
    reviews: 189,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 75,
  },
  {
    id: "fruit-7",
    name: "Sweet Watermelon",
    description: "Juicy, refreshing watermelon perfect for summer. Naturally sweet and hydrating.",
    price: 40,
    originalPrice: 55,
    image: "https://images.unsplash.com/photo-1563114773-84221bd62daa?w=400&q=80",
    category: "fruits",
    rating: 4.9,
    reviews: 345,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 60,
  },
  {
    id: "fruit-8",
    name: "Muskmelon",
    description: "Sweet, aromatic muskmelon with orange flesh. Refreshing summer treat.",
    price: 50,
    originalPrice: 65,
    image: "https://images.unsplash.com/photo-1571575173700-afb9492e6a50?w=400&q=80",
    category: "fruits",
    rating: 4.7,
    reviews: 178,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 55,
  },
  {
    id: "fruit-9",
    name: "Fresh Pineapple",
    description: "Tropical pineapple with sweet-tangy flavor. Perfect for juices and desserts.",
    price: 80,
    originalPrice: 100,
    image: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400&q=80",
    category: "fruits",
    rating: 4.8,
    reviews: 234,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 45,
  },
  {
    id: "fruit-10",
    name: "Pomegranate",
    description: "Ruby-red pomegranate seeds bursting with antioxidants. Nature's superfood.",
    price: 180,
    originalPrice: 220,
    image: "https://images.unsplash.com/photo-1541344999736-83eca272f6fc?w=400&q=80",
    category: "fruits",
    rating: 4.9,
    reviews: 289,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 70,
  },
  {
    id: "fruit-11",
    name: "Fresh Guava",
    description: "Fragrant guavas with pink flesh. Rich in Vitamin C and fiber.",
    price: 80,
    originalPrice: 100,
    image: "https://images.unsplash.com/photo-1536511132770-e5058c7e8c46?w=400&q=80",
    category: "fruits",
    rating: 4.6,
    reviews: 167,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 90,
  },
  {
    id: "fruit-12",
    name: "Fresh Kiwi",
    description: "Tangy green kiwis packed with Vitamin C. Perfect for smoothies and desserts.",
    price: 200,
    originalPrice: 250,
    image: "https://images.unsplash.com/photo-1585059895524-72359e06133a?w=400&q=80",
    category: "fruits",
    rating: 4.7,
    reviews: 145,
    isOrganic: true,
    isFresh: true,
    unit: "per 4 pieces",
    stock: 50,
  },
  {
    id: "fruit-13",
    name: "Fresh Strawberries",
    description: "Sweet, red strawberries perfect for desserts, smoothies, and snacking.",
    price: 250,
    originalPrice: 300,
    image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&q=80",
    category: "fruits",
    rating: 4.9,
    reviews: 312,
    isOrganic: true,
    isFresh: true,
    unit: "per 250g",
    stock: 40,
  },
  {
    id: "fruit-14",
    name: "Fresh Blueberries",
    description: "Antioxidant-rich blueberries. Perfect for breakfast bowls and baking.",
    price: 350,
    originalPrice: 420,
    image: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&q=80",
    category: "fruits",
    rating: 4.8,
    reviews: 198,
    isOrganic: true,
    isFresh: true,
    unit: "per 200g",
    stock: 35,
  },
  {
    id: "fruit-15",
    name: "Fresh Raspberries",
    description: "Delicate, sweet-tart raspberries. Premium berries for desserts.",
    price: 380,
    originalPrice: 450,
    image: "https://images.unsplash.com/photo-1577003833619-76bbd7f82948?w=400&q=80",
    category: "fruits",
    rating: 4.7,
    reviews: 134,
    isOrganic: true,
    isFresh: true,
    unit: "per 200g",
    stock: 30,
  },
  {
    id: "fruit-16",
    name: "Fresh Pears",
    description: "Juicy, sweet pears with buttery texture. Great for salads and snacking.",
    price: 160,
    originalPrice: 200,
    image: "https://images.unsplash.com/photo-1514756331096-242fdeb70d4a?w=400&q=80",
    category: "fruits",
    rating: 4.6,
    reviews: 156,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 65,
  },
  {
    id: "fruit-17",
    name: "Fresh Peaches",
    description: "Fragrant, fuzzy peaches with sweet flesh. Summer's most beloved fruit.",
    price: 200,
    originalPrice: 250,
    image: "https://images.unsplash.com/photo-1595124285205-3c2eb35c0a50?w=400&q=80",
    category: "fruits",
    rating: 4.8,
    reviews: 178,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 55,
  },
  {
    id: "fruit-18",
    name: "Fresh Plums",
    description: "Sweet, juicy plums with deep purple skin. Perfect for jams and eating fresh.",
    price: 180,
    originalPrice: 220,
    image: "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=400&q=80",
    category: "fruits",
    rating: 4.5,
    reviews: 123,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 50,
  },
  {
    id: "fruit-19",
    name: "Fresh Cherries",
    description: "Sweet, dark red cherries bursting with flavor. Premium seasonal treat.",
    price: 450,
    originalPrice: 550,
    image: "https://images.unsplash.com/photo-1528821128474-27f963b062bf?w=400&q=80",
    category: "fruits",
    rating: 4.9,
    reviews: 234,
    isOrganic: true,
    isFresh: true,
    unit: "per 500g",
    stock: 25,
  },
  {
    id: "fruit-20",
    name: "Custard Apple",
    description: "Creamy, sweet custard apple (sitafal) with unique flavor and texture.",
    price: 150,
    originalPrice: 180,
    image: "https://images.unsplash.com/photo-1568702846914-96b305d2uj20?w=400&q=80",
    category: "fruits",
    rating: 4.7,
    reviews: 145,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 40,
  },
  {
    id: "fruit-21",
    name: "Fresh Figs",
    description: "Honey-sweet fresh figs with delicate texture. Ancient superfood.",
    price: 280,
    originalPrice: 350,
    image: "https://images.unsplash.com/photo-1601379760591-1577c05fb98e?w=400&q=80",
    category: "fruits",
    rating: 4.8,
    reviews: 167,
    isOrganic: true,
    isFresh: true,
    unit: "per 500g",
    stock: 35,
  },
  {
    id: "fruit-22",
    name: "Fresh Jackfruit",
    description: "Tropical jackfruit with sweet, fibrous flesh. Largest tree-borne fruit.",
    price: 60,
    originalPrice: 80,
    image: "https://images.unsplash.com/photo-1528825871115-3581a5387919?w=400&q=80",
    category: "fruits",
    rating: 4.6,
    reviews: 98,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 30,
  },
  {
    id: "fruit-23",
    name: "Fresh Lychee",
    description: "Fragrant, juicy lychees with floral sweetness. Seasonal summer delicacy.",
    price: 220,
    originalPrice: 280,
    image: "https://images.unsplash.com/photo-1586285009838-67c0a7a9ae4c?w=400&q=80",
    category: "fruits",
    rating: 4.9,
    reviews: 256,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 45,
  },
  {
    id: "fruit-24",
    name: "Dragon Fruit",
    description: "Exotic pink dragon fruit with white flesh. Mildly sweet and refreshing.",
    price: 200,
    originalPrice: 250,
    image: "https://images.unsplash.com/photo-1527325678964-54921661f888?w=400&q=80",
    category: "fruits",
    rating: 4.7,
    reviews: 178,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 40,
  },
  {
    id: "fruit-25",
    name: "Fresh Avocado",
    description: "Creamy, nutritious avocados perfect for toast, guacamole, and salads.",
    price: 180,
    originalPrice: 220,
    image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&q=80",
    category: "fruits",
    rating: 4.8,
    reviews: 234,
    isOrganic: true,
    isFresh: true,
    unit: "per 2 pieces",
    stock: 50,
  },
  {
    id: "fruit-26",
    name: "Fresh Lemons",
    description: "Tangy, zesty lemons essential for cooking, drinks, and garnishing.",
    price: 80,
    originalPrice: 100,
    image: "https://images.unsplash.com/photo-1582287014914-1db39c258f76?w=400&q=80",
    category: "fruits",
    rating: 4.7,
    reviews: 289,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 120,
  },
  {
    id: "fruit-27",
    name: "Sweet Lime (Mosambi)",
    description: "Mild, sweet citrus fruit popular for fresh juice. Light and refreshing.",
    price: 100,
    originalPrice: 130,
    image: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=400&q=80",
    category: "fruits",
    rating: 4.6,
    reviews: 167,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 90,
  },
  {
    id: "fruit-28",
    name: "Fresh Dates",
    description: "Sweet, chewy dates packed with natural energy. Nature's candy.",
    price: 250,
    originalPrice: 300,
    image: "https://images.unsplash.com/photo-1612264330811-c6c485ca4a8e?w=400&q=80",
    category: "fruits",
    rating: 4.8,
    reviews: 198,
    isOrganic: true,
    isFresh: true,
    unit: "per 500g",
    stock: 60,
  },
  {
    id: "fruit-29",
    name: "Fresh Coconut",
    description: "Tender coconut with sweet water and soft malai. Ultimate refreshment.",
    price: 50,
    originalPrice: 65,
    image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400&q=80",
    category: "fruits",
    rating: 4.9,
    reviews: 345,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 80,
  },
  {
    id: "fruit-30",
    name: "Star Fruit",
    description: "Exotic star-shaped fruit with tangy-sweet flavor. Beautiful garnish.",
    price: 120,
    originalPrice: 150,
    image: "https://images.unsplash.com/photo-1533036431451-1e0671eabeda?w=400&q=80",
    category: "fruits",
    rating: 4.5,
    reviews: 87,
    isOrganic: true,
    isFresh: true,
    unit: "per 4 pieces",
    stock: 35,
  },
];
