// Grains & Pulses Category - 30 Products with Real Unsplash Images

import { Product } from "./vegetables";

export const grainsPulses: Product[] = [
  {
    id: "grain-1",
    name: "Premium Basmati Rice",
    description: "Long-grain aromatic basmati rice. Aged for perfect aroma and taste.",
    price: 180,
    originalPrice: 220,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80",
    category: "grains",
    rating: 4.9,
    reviews: 567,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 200,
  },
  {
    id: "grain-2",
    name: "Brown Rice",
    description: "Whole grain brown rice with bran intact. Fiber-rich and nutritious.",
    price: 120,
    originalPrice: 150,
    image: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=400&q=80",
    category: "grains",
    rating: 4.7,
    reviews: 345,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 150,
  },
  {
    id: "grain-3",
    name: "Sona Masoori Rice",
    description: "Light, aromatic Sona Masoori rice popular in South India.",
    price: 100,
    originalPrice: 130,
    image: "https://images.unsplash.com/photo-1516684732162-798a0062be99?w=400&q=80",
    category: "grains",
    rating: 4.8,
    reviews: 423,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 180,
  },
  {
    id: "grain-4",
    name: "Whole Wheat",
    description: "Premium quality wheat grains for making fresh atta at home.",
    price: 50,
    originalPrice: 65,
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&q=80",
    category: "grains",
    rating: 4.6,
    reviews: 289,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 250,
  },
  {
    id: "grain-5",
    name: "Whole Wheat Flour (Atta)",
    description: "Stone-ground whole wheat flour for soft, nutritious rotis.",
    price: 55,
    originalPrice: 70,
    image: "https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=400&q=80",
    category: "grains",
    rating: 4.8,
    reviews: 534,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 300,
  },
  {
    id: "grain-6",
    name: "Yellow Maize",
    description: "Sweet yellow corn/maize kernels for making makki roti and popcorn.",
    price: 45,
    originalPrice: 60,
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&q=80",
    category: "grains",
    rating: 4.5,
    reviews: 198,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 120,
  },
  {
    id: "grain-7",
    name: "Pearl Barley",
    description: "Polished barley grains for soups, salads, and healthy bowls.",
    price: 80,
    originalPrice: 100,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80",
    category: "grains",
    rating: 4.6,
    reviews: 145,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 80,
  },
  {
    id: "grain-8",
    name: "Rolled Oats",
    description: "Whole grain rolled oats for healthy breakfast. High fiber content.",
    price: 150,
    originalPrice: 180,
    image: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=400&q=80",
    category: "grains",
    rating: 4.8,
    reviews: 378,
    isOrganic: true,
    isFresh: true,
    unit: "per 500g",
    stock: 100,
  },
  {
    id: "grain-9",
    name: "Jowar (Sorghum)",
    description: "Gluten-free jowar millet for rotis and healthy preparations.",
    price: 60,
    originalPrice: 75,
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&q=80",
    category: "grains",
    rating: 4.7,
    reviews: 234,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 90,
  },
  {
    id: "grain-10",
    name: "Bajra (Pearl Millet)",
    description: "Nutritious bajra for winter rotis. Rich in iron and fiber.",
    price: 55,
    originalPrice: 70,
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&q=80",
    category: "grains",
    rating: 4.6,
    reviews: 189,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 85,
  },
  {
    id: "grain-11",
    name: "Ragi (Finger Millet)",
    description: "Calcium-rich ragi for dosa, porridge, and healthy baking.",
    price: 65,
    originalPrice: 80,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80",
    category: "grains",
    rating: 4.8,
    reviews: 312,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 75,
  },
  {
    id: "grain-12",
    name: "Toor Dal (Pigeon Pea)",
    description: "Premium toor dal for authentic sambar and dal preparations.",
    price: 160,
    originalPrice: 190,
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&q=80",
    category: "grains",
    rating: 4.8,
    reviews: 445,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 120,
  },
  {
    id: "grain-13",
    name: "Moong Dal (Split)",
    description: "Yellow split moong dal for light, digestible preparations.",
    price: 140,
    originalPrice: 170,
    image: "https://images.unsplash.com/photo-1515942140440-bc864f53a0cb?w=400&q=80",
    category: "grains",
    rating: 4.7,
    reviews: 367,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 100,
  },
  {
    id: "grain-14",
    name: "Masoor Dal (Red Lentils)",
    description: "Quick-cooking red lentils rich in protein. Comfort food staple.",
    price: 130,
    originalPrice: 160,
    image: "https://images.unsplash.com/photo-1551462147-37885acc36f1?w=400&q=80",
    category: "grains",
    rating: 4.8,
    reviews: 389,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 110,
  },
  {
    id: "grain-15",
    name: "Chana Dal",
    description: "Split Bengal gram for dal and traditional dishes like puran poli.",
    price: 120,
    originalPrice: 150,
    image: "https://images.unsplash.com/photo-1515942140440-bc864f53a0cb?w=400&q=80",
    category: "grains",
    rating: 4.6,
    reviews: 278,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 95,
  },
  {
    id: "grain-16",
    name: "Urad Dal (Black Gram)",
    description: "Split black gram essential for idli, dosa, and dal makhani.",
    price: 150,
    originalPrice: 180,
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&q=80",
    category: "grains",
    rating: 4.7,
    reviews: 334,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 85,
  },
  {
    id: "grain-17",
    name: "Whole Black Gram (Sabut Urad)",
    description: "Whole black gram with skin for authentic dal makhani.",
    price: 160,
    originalPrice: 200,
    image: "https://images.unsplash.com/photo-1551462147-37885acc36f1?w=400&q=80",
    category: "grains",
    rating: 4.8,
    reviews: 256,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 70,
  },
  {
    id: "grain-18",
    name: "Green Gram (Whole Moong)",
    description: "Whole green moong for sprouting and nutritious curries.",
    price: 140,
    originalPrice: 170,
    image: "https://images.unsplash.com/photo-1515942140440-bc864f53a0cb?w=400&q=80",
    category: "grains",
    rating: 4.7,
    reviews: 289,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 90,
  },
  {
    id: "grain-19",
    name: "Kabuli Chickpeas (Chole)",
    description: "Large, creamy white chickpeas for chole bhature and hummus.",
    price: 180,
    originalPrice: 220,
    image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=400&q=80",
    category: "grains",
    rating: 4.9,
    reviews: 456,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 100,
  },
  {
    id: "grain-20",
    name: "Rajma (Kidney Beans)",
    description: "Dark red kidney beans for authentic Rajma Chawal. Protein-rich.",
    price: 170,
    originalPrice: 210,
    image: "https://images.unsplash.com/photo-1551462147-37885acc36f1?w=400&q=80",
    category: "grains",
    rating: 4.8,
    reviews: 412,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 85,
  },
  {
    id: "grain-21",
    name: "Soybeans",
    description: "High-protein soybeans for making soy milk, tofu, and snacks.",
    price: 90,
    originalPrice: 110,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80",
    category: "grains",
    rating: 4.5,
    reviews: 178,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 65,
  },
  {
    id: "grain-22",
    name: "Horse Gram (Kulthi)",
    description: "Nutrient-dense horse gram for traditional soups and preparations.",
    price: 80,
    originalPrice: 100,
    image: "https://images.unsplash.com/photo-1551462147-37885acc36f1?w=400&q=80",
    category: "grains",
    rating: 4.4,
    reviews: 134,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 55,
  },
  {
    id: "grain-23",
    name: "Cowpeas (Lobia)",
    description: "Black-eyed peas for curries and salads. High in protein and fiber.",
    price: 100,
    originalPrice: 130,
    image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=400&q=80",
    category: "grains",
    rating: 4.6,
    reviews: 189,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 70,
  },
  {
    id: "grain-24",
    name: "Mixed Lentils",
    description: "Blend of nutritious lentils for quick, protein-rich meals.",
    price: 140,
    originalPrice: 170,
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&q=80",
    category: "grains",
    rating: 4.7,
    reviews: 234,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 80,
  },
  {
    id: "grain-25",
    name: "Pearl Millet (Kambu)",
    description: "Traditional pearl millet for South Indian porridge and rotis.",
    price: 55,
    originalPrice: 70,
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&q=80",
    category: "grains",
    rating: 4.6,
    reviews: 167,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 75,
  },
  {
    id: "grain-26",
    name: "Foxtail Millet",
    description: "Gluten-free foxtail millet for upma, rice alternatives, and porridge.",
    price: 70,
    originalPrice: 90,
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&q=80",
    category: "grains",
    rating: 4.7,
    reviews: 198,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 60,
  },
  {
    id: "grain-27",
    name: "Little Millet (Samai)",
    description: "Tiny, nutritious millet grains for rice substitutes and porridge.",
    price: 75,
    originalPrice: 95,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80",
    category: "grains",
    rating: 4.6,
    reviews: 145,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 55,
  },
  {
    id: "grain-28",
    name: "Barnyard Millet",
    description: "Fast-cooking barnyard millet for fasting foods and healthy meals.",
    price: 80,
    originalPrice: 100,
    image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&q=80",
    category: "grains",
    rating: 4.5,
    reviews: 123,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 50,
  },
  {
    id: "grain-29",
    name: "Kodo Millet",
    description: "Ancient kodo millet for diabetic-friendly meals and traditional dishes.",
    price: 85,
    originalPrice: 105,
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&q=80",
    category: "grains",
    rating: 4.7,
    reviews: 156,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 45,
  },
  {
    id: "grain-30",
    name: "Organic Mixed Grains",
    description: "Premium blend of millets and grains for nutritious multi-grain atta.",
    price: 120,
    originalPrice: 150,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80",
    category: "grains",
    rating: 4.8,
    reviews: 267,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 70,
  },
];
