// Leafy Greens Category - 30 Products with Real Unsplash Images

import { Product } from "./vegetables";

export const leafyGreens: Product[] = [
  {
    id: "leafy-1",
    name: "Fresh Spinach",
    description: "Nutrient-packed spinach leaves rich in iron. Perfect for palak dishes and smoothies.",
    price: 40,
    originalPrice: 55,
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80",
    category: "leafy-greens",
    rating: 4.9,
    reviews: 378,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 120,
  },
  {
    id: "leafy-2",
    name: "Fresh Coriander",
    description: "Aromatic coriander leaves (dhania) essential for Indian cooking and garnishing.",
    price: 25,
    originalPrice: 35,
    image: "https://images.unsplash.com/photo-1604514628550-37477afdf4e3?w=400&q=80",
    category: "leafy-greens",
    rating: 4.8,
    reviews: 445,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 150,
  },
  {
    id: "leafy-3",
    name: "Fresh Mint Leaves",
    description: "Refreshing mint (pudina) leaves for chutneys, drinks, and garnishing.",
    price: 30,
    originalPrice: 40,
    image: "https://images.unsplash.com/photo-1628557044797-f21d05d25a0a?w=400&q=80",
    category: "leafy-greens",
    rating: 4.9,
    reviews: 389,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 130,
  },
  {
    id: "leafy-4",
    name: "Fenugreek Leaves (Methi)",
    description: "Slightly bitter fenugreek leaves perfect for methi paratha and sabzi.",
    price: 35,
    originalPrice: 45,
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&q=80",
    category: "leafy-greens",
    rating: 4.7,
    reviews: 267,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 100,
  },
  {
    id: "leafy-5",
    name: "Curry Leaves",
    description: "Aromatic curry leaves essential for South Indian tempering and curries.",
    price: 20,
    originalPrice: 30,
    image: "https://images.unsplash.com/photo-1613467679035-4e9b0b1b2e7d?w=400&q=80",
    category: "leafy-greens",
    rating: 4.8,
    reviews: 356,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 140,
  },
  {
    id: "leafy-6",
    name: "Mustard Greens (Sarson)",
    description: "Peppery mustard greens for authentic sarson ka saag. Winter specialty.",
    price: 40,
    originalPrice: 50,
    image: "https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=400&q=80",
    category: "leafy-greens",
    rating: 4.6,
    reviews: 198,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 85,
  },
  {
    id: "leafy-7",
    name: "Dill Leaves (Suwa)",
    description: "Feathery dill leaves with anise-like flavor. Great for pickles and fish.",
    price: 35,
    originalPrice: 45,
    image: "https://images.unsplash.com/photo-1615485737651-5765caba1c92?w=400&q=80",
    category: "leafy-greens",
    rating: 4.5,
    reviews: 134,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 70,
  },
  {
    id: "leafy-8",
    name: "Amaranthus (Chaulai)",
    description: "Nutritious amaranth leaves rich in protein. Traditional Indian green.",
    price: 30,
    originalPrice: 40,
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&q=80",
    category: "leafy-greens",
    rating: 4.6,
    reviews: 145,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 80,
  },
  {
    id: "leafy-9",
    name: "Fresh Kale",
    description: "Superfood kale leaves packed with vitamins. Perfect for salads and smoothies.",
    price: 80,
    originalPrice: 100,
    image: "https://images.unsplash.com/photo-1524179091875-bf99a9a6af57?w=400&q=80",
    category: "leafy-greens",
    rating: 4.8,
    reviews: 234,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 60,
  },
  {
    id: "leafy-10",
    name: "Green Lettuce",
    description: "Crisp, fresh green lettuce for salads and sandwiches. Light and refreshing.",
    price: 50,
    originalPrice: 65,
    image: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400&q=80",
    category: "leafy-greens",
    rating: 4.7,
    reviews: 189,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 75,
  },
  {
    id: "leafy-11",
    name: "Iceberg Lettuce",
    description: "Crunchy iceberg lettuce with mild flavor. Classic salad ingredient.",
    price: 60,
    originalPrice: 80,
    image: "https://images.unsplash.com/photo-1563093718689-e5f4e7d15b4b?w=400&q=80",
    category: "leafy-greens",
    rating: 4.6,
    reviews: 167,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 65,
  },
  {
    id: "leafy-12",
    name: "Romaine Lettuce",
    description: "Elongated romaine lettuce perfect for Caesar salads. Crisp and nutritious.",
    price: 70,
    originalPrice: 90,
    image: "https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?w=400&q=80",
    category: "leafy-greens",
    rating: 4.7,
    reviews: 145,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 55,
  },
  {
    id: "leafy-13",
    name: "Swiss Chard",
    description: "Colorful Swiss chard with rainbow stems. Mild flavor, packed with nutrients.",
    price: 75,
    originalPrice: 95,
    image: "https://images.unsplash.com/photo-1591985666643-1edc4f0e8d02?w=400&q=80",
    category: "leafy-greens",
    rating: 4.5,
    reviews: 98,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 45,
  },
  {
    id: "leafy-14",
    name: "Fresh Basil",
    description: "Aromatic sweet basil perfect for Italian dishes, Thai curries, and pesto.",
    price: 50,
    originalPrice: 65,
    image: "https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=400&q=80",
    category: "leafy-greens",
    rating: 4.9,
    reviews: 278,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 90,
  },
  {
    id: "leafy-15",
    name: "Fresh Parsley",
    description: "Bright, fresh parsley for garnishing and cooking. Adds fresh flavor to dishes.",
    price: 45,
    originalPrice: 60,
    image: "https://images.unsplash.com/photo-1599436837639-a8f30ee17f66?w=400&q=80",
    category: "leafy-greens",
    rating: 4.7,
    reviews: 167,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 85,
  },
  {
    id: "leafy-16",
    name: "Celery Leaves",
    description: "Aromatic celery leaves for soups, salads, and garnishing. Adds depth to dishes.",
    price: 55,
    originalPrice: 70,
    image: "https://images.unsplash.com/photo-1580391564590-aeca65c5e2d3?w=400&q=80",
    category: "leafy-greens",
    rating: 4.5,
    reviews: 123,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 60,
  },
  {
    id: "leafy-17",
    name: "Fresh Arugula",
    description: "Peppery arugula (rocket) leaves perfect for salads and pizza toppings.",
    price: 80,
    originalPrice: 100,
    image: "https://images.unsplash.com/photo-1593048951071-38c36e0d3dc3?w=400&q=80",
    category: "leafy-greens",
    rating: 4.6,
    reviews: 145,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 50,
  },
  {
    id: "leafy-18",
    name: "Fresh Watercress",
    description: "Peppery watercress perfect for salads and sandwiches. Nutrient-dense superfood.",
    price: 70,
    originalPrice: 90,
    image: "https://images.unsplash.com/photo-1563223771-5fe4038a0caa?w=400&q=80",
    category: "leafy-greens",
    rating: 4.5,
    reviews: 89,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 40,
  },
  {
    id: "leafy-19",
    name: "Sorrel Leaves",
    description: "Tangy sorrel leaves with lemony flavor. Great for soups and salads.",
    price: 65,
    originalPrice: 85,
    image: "https://images.unsplash.com/photo-1567375698348-5d9d5ae99de0?w=400&q=80",
    category: "leafy-greens",
    rating: 4.4,
    reviews: 67,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 35,
  },
  {
    id: "leafy-20",
    name: "Malabar Spinach",
    description: "Thick-leaved Malabar spinach (poi) popular in coastal cuisines.",
    price: 35,
    originalPrice: 45,
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80",
    category: "leafy-greens",
    rating: 4.5,
    reviews: 112,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 55,
  },
  {
    id: "leafy-21",
    name: "Colocasia Leaves (Arbi Patta)",
    description: "Large colocasia leaves for making patra and aloo vadi. Traditional delicacy.",
    price: 40,
    originalPrice: 50,
    image: "https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=400&q=80",
    category: "leafy-greens",
    rating: 4.6,
    reviews: 98,
    isOrganic: true,
    isFresh: true,
    unit: "per 10 leaves",
    stock: 45,
  },
  {
    id: "leafy-22",
    name: "Drumstick Leaves (Moringa)",
    description: "Nutrient-dense moringa leaves, one of the most nutritious plants on earth.",
    price: 50,
    originalPrice: 65,
    image: "https://images.unsplash.com/photo-1609501676725-7186f017a4b7?w=400&q=80",
    category: "leafy-greens",
    rating: 4.9,
    reviews: 234,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 70,
  },
  {
    id: "leafy-23",
    name: "Radish Leaves",
    description: "Peppery radish greens, often discarded but highly nutritious.",
    price: 25,
    originalPrice: 35,
    image: "https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=400&q=80",
    category: "leafy-greens",
    rating: 4.4,
    reviews: 78,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 60,
  },
  {
    id: "leafy-24",
    name: "Turnip Greens",
    description: "Slightly bitter turnip leaves, excellent for traditional preparations.",
    price: 30,
    originalPrice: 40,
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&q=80",
    category: "leafy-greens",
    rating: 4.3,
    reviews: 56,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 50,
  },
  {
    id: "leafy-25",
    name: "Beet Greens",
    description: "Colorful beetroot leaves rich in vitamins. Often overlooked superfood.",
    price: 35,
    originalPrice: 45,
    image: "https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?w=400&q=80",
    category: "leafy-greens",
    rating: 4.5,
    reviews: 89,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 55,
  },
  {
    id: "leafy-26",
    name: "Spring Onion Greens",
    description: "Fresh green tops of spring onions. Mild onion flavor for garnishing.",
    price: 30,
    originalPrice: 40,
    image: "https://images.unsplash.com/photo-1580294647332-55a05e2e481e?w=400&q=80",
    category: "leafy-greens",
    rating: 4.6,
    reviews: 134,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 80,
  },
  {
    id: "leafy-27",
    name: "Garlic Chives",
    description: "Flat-leaved garlic chives with mild garlic flavor. Asian cuisine essential.",
    price: 45,
    originalPrice: 55,
    image: "https://images.unsplash.com/photo-1580294647332-55a05e2e481e?w=400&q=80",
    category: "leafy-greens",
    rating: 4.6,
    reviews: 112,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 65,
  },
  {
    id: "leafy-28",
    name: "Leek Greens",
    description: "Tender green parts of leeks with mild onion-garlic flavor.",
    price: 55,
    originalPrice: 70,
    image: "https://images.unsplash.com/photo-1558818498-28c1e002b655?w=400&q=80",
    category: "leafy-greens",
    rating: 4.5,
    reviews: 78,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 45,
  },
  {
    id: "leafy-29",
    name: "Fresh Bok Choy",
    description: "Crisp Asian bok choy with mild flavor. Perfect for stir-fries and soups.",
    price: 70,
    originalPrice: 90,
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80",
    category: "leafy-greens",
    rating: 4.7,
    reviews: 156,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 55,
  },
  {
    id: "leafy-30",
    name: "Chinese Cabbage",
    description: "Elongated Chinese cabbage (napa) perfect for Asian dishes and kimchi.",
    price: 60,
    originalPrice: 75,
    image: "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=400&q=80",
    category: "leafy-greens",
    rating: 4.6,
    reviews: 123,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 50,
  },
];
