// Vegetables Category - 30 Products with Real Unsplash Images

export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  image: string;
  category: string;
  rating: number;
  reviews: number;
  isOrganic: boolean;
  isFresh: boolean;
  unit: string;
  stock: number;
}

export const vegetables: Product[] = [
  {
    id: "veg-1",
    name: "Fresh Tomatoes",
    description: "Juicy, vine-ripened red tomatoes perfect for salads, curries, and cooking. Handpicked from our organic farms.",
    price: 45,
    originalPrice: 60,
    image: "https://images.unsplash.com/photo-1546470427-0d4db154ceb8?w=400&q=80",
    category: "vegetables",
    rating: 4.8,
    reviews: 324,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 150,
  },
  {
    id: "veg-2",
    name: "Farm Fresh Potatoes",
    description: "Earthy, versatile potatoes ideal for frying, mashing, or roasting. Grown in mineral-rich soil.",
    price: 35,
    originalPrice: 45,
    image: "https://images.unsplash.com/photo-1518977676601-b53f82ber9eb?w=400&q=80",
    category: "vegetables",
    rating: 4.6,
    reviews: 256,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 200,
  },
  {
    id: "veg-3",
    name: "Red Onions",
    description: "Pungent and flavorful red onions, essential for every kitchen. Adds depth to any dish.",
    price: 40,
    originalPrice: 55,
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400&q=80",
    category: "vegetables",
    rating: 4.5,
    reviews: 198,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 180,
  },
  {
    id: "veg-4",
    name: "Organic Carrots",
    description: "Sweet, crunchy orange carrots rich in beta-carotene. Perfect for salads, juices, and cooking.",
    price: 55,
    originalPrice: 70,
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&q=80",
    category: "vegetables",
    rating: 4.9,
    reviews: 287,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 120,
  },
  {
    id: "veg-5",
    name: "Fresh Brinjal",
    description: "Glossy purple eggplants with tender flesh. Ideal for bhartha, curries, and grilling.",
    price: 50,
    originalPrice: 65,
    image: "https://images.unsplash.com/photo-1615484477778-ca3b77940c25?w=400&q=80",
    category: "vegetables",
    rating: 4.4,
    reviews: 156,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 90,
  },
  {
    id: "veg-6",
    name: "Green Cabbage",
    description: "Crisp, leafy green cabbage perfect for salads, stir-fries, and coleslaw.",
    price: 30,
    originalPrice: 40,
    image: "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=400&q=80",
    category: "vegetables",
    rating: 4.6,
    reviews: 134,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 75,
  },
  {
    id: "veg-7",
    name: "Fresh Cauliflower",
    description: "Snow-white cauliflower florets with tight curds. Great for gobi dishes and roasting.",
    price: 45,
    originalPrice: 60,
    image: "https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=400&q=80",
    category: "vegetables",
    rating: 4.7,
    reviews: 178,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 80,
  },
  {
    id: "veg-8",
    name: "Lady Finger (Okra)",
    description: "Tender green okra pods, perfect for bhindi masala and crispy fried preparations.",
    price: 60,
    originalPrice: 75,
    image: "https://images.unsplash.com/photo-1425543103986-22abb7d7e8d2?w=400&q=80",
    category: "vegetables",
    rating: 4.5,
    reviews: 145,
    isOrganic: true,
    isFresh: true,
    unit: "per 500g",
    stock: 100,
  },
  {
    id: "veg-9",
    name: "Fresh Beetroot",
    description: "Deep red beetroots rich in iron and antioxidants. Perfect for salads and juices.",
    price: 50,
    originalPrice: 65,
    image: "https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?w=400&q=80",
    category: "vegetables",
    rating: 4.8,
    reviews: 167,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 85,
  },
  {
    id: "veg-10",
    name: "White Radish",
    description: "Crisp, peppery white radish (mooli) great for salads, parathas, and pickling.",
    price: 35,
    originalPrice: 45,
    image: "https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=400&q=80",
    category: "vegetables",
    rating: 4.4,
    reviews: 98,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 95,
  },
  {
    id: "veg-11",
    name: "Green Chilli",
    description: "Spicy green chilies to add heat to any dish. Farm-fresh and packed with flavor.",
    price: 80,
    originalPrice: 100,
    image: "https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400&q=80",
    category: "vegetables",
    rating: 4.7,
    reviews: 234,
    isOrganic: true,
    isFresh: true,
    unit: "per 250g",
    stock: 200,
  },
  {
    id: "veg-12",
    name: "Bell Pepper (Capsicum)",
    description: "Colorful bell peppers - sweet, crunchy, and perfect for salads and stir-fries.",
    price: 120,
    originalPrice: 150,
    image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=80",
    category: "vegetables",
    rating: 4.6,
    reviews: 189,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 70,
  },
  {
    id: "veg-13",
    name: "Bottle Gourd (Lauki)",
    description: "Light, nutritious bottle gourd perfect for healthy curries and soups.",
    price: 40,
    originalPrice: 50,
    image: "https://images.unsplash.com/photo-1571686183266-b6f4b6e39d0f?w=400&q=80",
    category: "vegetables",
    rating: 4.3,
    reviews: 87,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 60,
  },
  {
    id: "veg-14",
    name: "Ridge Gourd (Turai)",
    description: "Tender ridge gourd with distinct ridges. Great for light, digestible preparations.",
    price: 45,
    originalPrice: 55,
    image: "https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=400&q=80",
    category: "vegetables",
    rating: 4.4,
    reviews: 76,
    isOrganic: true,
    isFresh: true,
    unit: "per 500g",
    stock: 55,
  },
  {
    id: "veg-15",
    name: "Bitter Gourd (Karela)",
    description: "Bitter melon known for its health benefits. Ideal for traditional preparations.",
    price: 55,
    originalPrice: 70,
    image: "https://images.unsplash.com/photo-1594995846645-f5d68d1d8aa8?w=400&q=80",
    category: "vegetables",
    rating: 4.2,
    reviews: 65,
    isOrganic: true,
    isFresh: true,
    unit: "per 500g",
    stock: 45,
  },
  {
    id: "veg-16",
    name: "Snake Gourd",
    description: "Long, slender snake gourd with mild flavor. Popular in South Indian cuisine.",
    price: 50,
    originalPrice: 60,
    image: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=400&q=80",
    category: "vegetables",
    rating: 4.3,
    reviews: 54,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 40,
  },
  {
    id: "veg-17",
    name: "Orange Pumpkin",
    description: "Sweet, vibrant orange pumpkin perfect for halwa, curries, and soups.",
    price: 35,
    originalPrice: 45,
    image: "https://images.unsplash.com/photo-1506917728037-b6af01a7d403?w=400&q=80",
    category: "vegetables",
    rating: 4.7,
    reviews: 123,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 65,
  },
  {
    id: "veg-18",
    name: "Sweet Corn",
    description: "Golden, sweet corn cobs bursting with flavor. Perfect for grilling and salads.",
    price: 30,
    originalPrice: 40,
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&q=80",
    category: "vegetables",
    rating: 4.8,
    reviews: 245,
    isOrganic: true,
    isFresh: true,
    unit: "per 2 pieces",
    stock: 100,
  },
  {
    id: "veg-19",
    name: "French Beans",
    description: "Crisp, tender French beans with delicate flavor. Ideal for stir-fries and salads.",
    price: 70,
    originalPrice: 85,
    image: "https://images.unsplash.com/photo-1567375698348-5d9d5ae99de0?w=400&q=80",
    category: "vegetables",
    rating: 4.6,
    reviews: 134,
    isOrganic: true,
    isFresh: true,
    unit: "per 500g",
    stock: 75,
  },
  {
    id: "veg-20",
    name: "Cluster Beans (Gawar)",
    description: "Nutritious cluster beans rich in fiber. Traditional vegetable for sabzi dishes.",
    price: 65,
    originalPrice: 80,
    image: "https://images.unsplash.com/photo-1595855759920-86582396756a?w=400&q=80",
    category: "vegetables",
    rating: 4.4,
    reviews: 89,
    isOrganic: true,
    isFresh: true,
    unit: "per 500g",
    stock: 60,
  },
  {
    id: "veg-21",
    name: "Fresh Drumstick",
    description: "Long, nutritious drumsticks (moringa pods) perfect for sambar and curries.",
    price: 60,
    originalPrice: 75,
    image: "https://images.unsplash.com/photo-1609501676725-7186f017a4b7?w=400&q=80",
    category: "vegetables",
    rating: 4.7,
    reviews: 156,
    isOrganic: true,
    isFresh: true,
    unit: "per 500g",
    stock: 50,
  },
  {
    id: "veg-22",
    name: "Fresh Turnip",
    description: "Crisp, slightly sweet turnips perfect for roasting and adding to stews.",
    price: 45,
    originalPrice: 55,
    image: "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=400&q=80",
    category: "vegetables",
    rating: 4.3,
    reviews: 67,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 55,
  },
  {
    id: "veg-23",
    name: "Green Zucchini",
    description: "Tender green zucchini with mild flavor. Great for grilling and healthy pasta.",
    price: 90,
    originalPrice: 110,
    image: "https://images.unsplash.com/photo-1596262259863-1c9e3b887f8e?w=400&q=80",
    category: "vegetables",
    rating: 4.5,
    reviews: 112,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 45,
  },
  {
    id: "veg-24",
    name: "Fresh Broccoli",
    description: "Nutrient-rich broccoli florets packed with vitamins. Perfect for healthy meals.",
    price: 120,
    originalPrice: 150,
    image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400&q=80",
    category: "vegetables",
    rating: 4.8,
    reviews: 198,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 60,
  },
  {
    id: "veg-25",
    name: "Spring Onion",
    description: "Fresh spring onions with mild, sweet flavor. Perfect garnish for Asian dishes.",
    price: 40,
    originalPrice: 50,
    image: "https://images.unsplash.com/photo-1580294647332-55a05e2e481e?w=400&q=80",
    category: "vegetables",
    rating: 4.6,
    reviews: 145,
    isOrganic: true,
    isFresh: true,
    unit: "per bunch",
    stock: 80,
  },
  {
    id: "veg-26",
    name: "Button Mushroom",
    description: "Fresh white button mushrooms with earthy flavor. Great for pizzas and curries.",
    price: 150,
    originalPrice: 180,
    image: "https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=400&q=80",
    category: "vegetables",
    rating: 4.7,
    reviews: 234,
    isOrganic: true,
    isFresh: true,
    unit: "per 200g",
    stock: 40,
  },
  {
    id: "veg-27",
    name: "Fresh Lettuce",
    description: "Crisp, fresh lettuce leaves perfect for salads, wraps, and burgers.",
    price: 60,
    originalPrice: 75,
    image: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400&q=80",
    category: "vegetables",
    rating: 4.5,
    reviews: 167,
    isOrganic: true,
    isFresh: true,
    unit: "per piece",
    stock: 55,
  },
  {
    id: "veg-28",
    name: "Taro Root (Arbi)",
    description: "Starchy taro root with nutty flavor. Traditional ingredient for festive dishes.",
    price: 55,
    originalPrice: 70,
    image: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=400&q=80",
    category: "vegetables",
    rating: 4.4,
    reviews: 78,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 50,
  },
  {
    id: "veg-29",
    name: "Fresh Yam (Suran)",
    description: "Large, starchy yam with mild taste. Popular for frying and curry preparations.",
    price: 50,
    originalPrice: 65,
    image: "https://images.unsplash.com/photo-1596097635121-14b38e5f9f91?w=400&q=80",
    category: "vegetables",
    rating: 4.3,
    reviews: 56,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 45,
  },
  {
    id: "veg-30",
    name: "Ash Gourd (Petha)",
    description: "Large, waxy ash gourd used for sweets and healthy preparations.",
    price: 30,
    originalPrice: 40,
    image: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=400&q=80",
    category: "vegetables",
    rating: 4.2,
    reviews: 45,
    isOrganic: true,
    isFresh: true,
    unit: "per kg",
    stock: 35,
  },
];
